server:
  port: 8000
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "G8ayHDyXHyL3OAU5+YDBmy7K2LxFNGM+WoKdMta7BRqW+BVPYIi2qb1eXfhYIEII"